/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TripContainer: typeof import('./components/TripContainer.vue')['default']
    TripDetailMap: typeof import('./components/TripDetailMap.vue')['default']
    TripFilters: typeof import('./components/TripFilters.vue')['default']
    TripList: typeof import('./components/TripList.vue')['default']
  }
}
